#if !canImport(ObjectiveC)
import XCTest

extension MD5Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MD5Tests = [
        ("testMD5", testMD5),
        ("testSHA1", testSHA1),
        ("testSHA256", testSHA256),
        ("testSHA384", testSHA384),
        ("testSHA512", testSHA512),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MD5Tests.__allTests__MD5Tests),
    ]
}
#endif
