#if !canImport(ObjectiveC)
import XCTest

extension AESTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AESTests = [
        ("testAESGCM", testAESGCM),
    ]
}

extension DigestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DigestTests = [
        ("testMD5", testMD5),
        ("testSHA1", testSHA1),
        ("testSHA256", testSHA256),
        ("testSHA384", testSHA384),
        ("testSHA512", testSHA512),
    ]
}

extension MACTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MACTests = [
        ("testMD5", testMD5),
        ("testSHA1", testSHA1),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AESTests.__allTests__AESTests),
        testCase(DigestTests.__allTests__DigestTests),
        testCase(MACTests.__allTests__MACTests),
    ]
}
#endif
